<div class="left news-article">

    <p>A Szekszárdi Kutyamenhelyen több mint 200 védencünkkel várjuk látogatóinkat minden szombaton 10:00 - 15:30 között Szekszárdon, a Bogyiszlói út 8-as szám alatt.</p>

    <img class="about-img" src="/Content/Images/about.jpg" alt="">
    <p>Telefon:&nbsp+36&nbsp20/981-05-58<br>Email:&nbsptmallatvedo@gmail.com<br>Számlaszám:&nbsp11746005-20009812<br>Iban:&nbspHU3711746005-20009812-00000000<br>SWIFT&nbspkód:&nbspOTPV-HU-HB<br>PayPal:&nbsptmallatvedo@gmail.com</p>
    <p>Célunk a Szekszárdi Állatotthon fenntartása és üzemeltetése, a városban talált gazdátlan állatok mentése, gondozása és új gazdáknál való elhelyezése. Büszkék vagyunk rá, hogy tevékenységünk eredményeként a Szekszárdon befogott kutyák nem kerülnek gyepmesteri telepre. Feladatunknak tekintjük közreműködni az állatvédelemmel kapcsolatos tennivalók végrehajtásában, segédkezni az állatvédelmi törvény rendeleteinek betartatásában. Közreműködünk az országos környezet- és természetvédelmi feladatok végrehajtásában is. Az állattartási kultúra fejlesztése; az állattartóknak az előírások betartására és a szakmai ismeretek bővítésére való nevelése ugyancsak fontos célunk. Elköteleztük magunkat a társadalomnak – elsősorban az ifjúságnak – a természet, különösen az élővilág szeretetére való nevelésére. Kampányokat szervezünk, tájékoztató és ismeretterjesztő munkát végzünk, állatvédelmi programokat szervezünk: kutyaiskolát, napközis tábort, családi programokat stb.</p>

    <p>Az alapítványunk tevékenységét egy öttagú kuratórium irányítja, napi szinten pedig a kuratórium elnöke és alelnöke felügyeli a munkát. Tagjai anyagi támogatásban nem részesülnek. Bevételünket teljes mértékben az állatok gondozására, állatorvosi kezelésére, ivartalanítására és kennelek, boxok építésére használjuk fel. A munkák elvégzésében napi szinten öt, heti szinten 13 ember segédkezik. A pártoló tagok száma meghaladja az 500 főt. Folyamatosan 140-220 kutyáról gondoskodunk. Minden szombaton nyílt napot tartunk, amikor családok és gyerekek látogatnak el az állatotthonunkba. Ilyenkor a gyerekek megtanulják az állatokkal való helyes bánásmódot. Megismerik az állatok szokásait és viselkedését, megtanulják, hogy az állattartás felelősséggel jár. A nyílt napokon évente átlagosan 1500 személy keresi fel az állatotthonunkat.</p>

    <p>Célunk a Szekszárdi Állatotthon fenntartása és üzemeltetése, a városban talált gazdátlan állatok mentése, gondozása és új gazdáknál való elhelyezése. Büszkék vagyunk rá, hogy tevékenységünk eredményeként a Szekszárdon befogott kutyák nem kerülnek gyepmesteri telepre. Feladatunknak tekintjük közreműködni az állatvédelemmel kapcsolatos tennivalók végrehajtásában, segédkezni az állatvédelmi törvény rendeleteinek betartatásában. Közreműködünk az országos környezet- és természetvédelmi feladatok végrehajtásában is. Az állattartási kultúra fejlesztése; az állattartóknak az előírások betartására és a szakmai ismeretek bővítésére való nevelése ugyancsak fontos célunk. Elköteleztük magunkat a társadalomnak – elsősorban az ifjúságnak – a természet, különösen az élővilág szeretetére való nevelésére. Kampányokat szervezünk, tájékoztató és ismeretterjesztő munkát végzünk, állatvédelmi programokat szervezünk: kutyaiskolát, napközis tábort, családi programokat stb.</p>

    <p>Az alapítványunk tevékenységét egy öttagú kuratórium irányítja, napi szinten pedig a kuratórium elnöke és alelnöke felügyeli a munkát. Tagjai anyagi támogatásban nem részesülnek. Bevételünket teljes mértékben az állatok gondozására, állatorvosi kezelésére, ivartalanítására és kennelek, boxok építésére használjuk fel. A munkák elvégzésében napi szinten öt, heti szinten 13 ember segédkezik. A pártoló tagok száma meghaladja az 500 főt. Folyamatosan 140-220 kutyáról gondoskodunk. Minden szombaton nyílt napot tartunk, amikor családok és gyerekek látogatnak el az állatotthonunkba. Ilyenkor a gyerekek megtanulják az állatokkal való helyes bánásmódot. Megismerik az állatok szokásait és viselkedését, megtanulják, hogy az állattartás felelősséggel jár. A nyílt napokon évente átlagosan 1500 személy keresi fel az állatotthonunkat.</p>

    <p>2001-ben a MÚOSZ Állatvédő Szakosztálya „Az év állatotthona” címet adományozta a szervezetünknek. Az alapítványunk 2002 óta tagja az RSPCA-nak (Angol Királyi Állatvédő Liga). Az RSPCA kérésére alapítványunk volt az egyik fő szervezője a 2004 februárjában megtartott RSPCA képzésnek, melynek szervezése már 2003 szeptemberében megkezdődött. 2003-ban beléptünk a Magyar Állatvédők Országos Szövetségébe.</p>

    <p>2003 nyarán országos népi kezdeményezésen alapuló aláírásgyűjtést indítottunk annak érdekében, hogy az országgyűlés bűncselekménynek minősítse az állatkínzást. A kezdeményezést mintegy 400 ezer felnőtt magyar ember támogatta aláírásával. 2004. március 8-án az Országgyűlés 284 igen szavazattal, 11 ellenében, 4 tartózkodás mellett elfogadta a Büntető törvénykönyv azon módosítását, amely bűncselekménynek minősítette az állatkínzást.</p>

    <p>2004 októberében a Magyar Állatorvosi Kamara "Az Év Állatvédelmi Díja 2004." elismerést adományozta az alapítványunknak a rendkívül eredményes népi kezdeményezésért.</p>

    <p>2005 januárjában alapítványunk kezdeményezésére megalakult a PetárdaSTOP Munkacsoport, melyhez néhány hét alatt 121 civil szervezet csatlakozott. Részben a törekvéseinknek köszönhetően a kormány a szilveszteri időszakra is betiltotta a petárdák használatát, és javaslatot tett a parlamentnek a maximálisan kiszabható szabálysértési bírság összegének 50-ről 100 ezer forintra emelésére.</p>

    <p>2007-ben a Tolna Megyei Közgyűlés Elnöke „Az Év Tolna Megyei Civil Szervezete 2006” különdíjat adományozta az alapítványunknak megköszönve ezzel a gesztussal a szervezetünk tíz évnyi eredményes munkáját.</p>

    <p>2008 augusztusában a Tolna Megyei Állat- és Természetvédő Alapítvány három éves szélmalomharcának köszönhetően Dombóváron megszüntették a kutya-róka viadalra szánt rókák tartását, és az állatviadalnak számító kotorékversenyek szervezését.</p>


</div>